#!/bin/bash
# chkconfig: 2345 80 20
# description: undefined
waittime=0
waitExit(){
   while true;do
   if [ ! -d "/proc/$1" ]; then
       echo "process is finished"
       break
    else
      waittime=$(($waittime+1))
      sleep 1s
      echo "process is alive " $waittime
    fi
    if [ "$waittime" -eq 10 ]; then
      kill -9 $1
      break

    fi
   done
}
running(){
if [ -f $PID_PATH_NAME ]; then
    PID=$(cat $PID_PATH_NAME)
    if [ -d "/proc/$PID" ]; then
      return 1
    else
      return 0
    fi
  else
   return 0
  fi
}
printRed(){
 echo -e "\033[31m$1\033[0m"
}
printGreen(){
 echo -e "\033[32m$1\033[0m"
}
SERVICE_NAME=undefined
PID_PATH_NAME=~/run/undefined-pid
case $1 in
    start)
        echo "Starting $SERVICE_NAME ..."
	running
        if [ ! $? -eq 1 ]; then
            nohup undefined /tmp 2>> /dev/null >> /dev/null &
                        echo $! > $PID_PATH_NAME
            printGreen "$SERVICE_NAME started ..."
        else
            printRed "$SERVICE_NAME is already running ..."
        fi
    ;;
    console)
       undefined
    ;;
    status)
      running
      if [ $? -eq 1 ]; then
        printGreen "running "
      else
        printRed "not running"
      fi
    ;;
    stop)
	running
        if [ $? -eq 1 ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stoping ..."
            kill  $PID;
	    waitExit $PID;
            printRed "$SERVICE_NAME stopped ..."
            rm $PID_PATH_NAME
        else
            printRed "$SERVICE_NAME is not running ..."
        fi
    ;;
    restart)
	running
        if [ $? -eq 1 ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stopping ...";
            kill  $PID;
	    waitExit $PID;
            echo "$SERVICE_NAME stopped ...";
            rm $PID_PATH_NAME
            echo "$SERVICE_NAME starting ..."
            nohup undefined /tmp 2>> /dev/null >> /dev/null &
                        echo $! > $PID_PATH_NAME
            printGreen "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME starting ..."
            nohup undefined /tmp 2>> /dev/null >> /dev/null &
                        echo $! > $PID_PATH_NAME
            printGreen "$SERVICE_NAME started ..."
        fi
    ;;
esac